version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
              python main.py -s f -t r 84.2 -a 543.5
              python main.py -s c -t k -45.14 -a 227.51
